title: Gabriel — ML Research
name: Gabriel Dax
description: ML Research Engineer
baseurl: ""
url: "https://g4br1el.github.io"
avatar: /images/self.png

markdown: kramdown

include:
  - _pages

collections:
  projects:
    output: true
    permalink: /projects/:title/

defaults:
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: page
  - scope:
      path: "_projects"
      type: projects
    values:
      layout: post

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-scholar

footer-links:
  github: g4br1el
  linkedin: gadax
  email: gabriel.dax@iis.fraunhofer.de
  scholar: UfJMwAQAAAAJ


scholar:
  style: ieee-with-url
  locale: en
  sort_by: year
  order: ascending
  source: ./_bibliography
  bibliography: references.bib
  bibliography_template: bib2
  replace_strings: true
  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details
  query: "@*"

exclude:
  - Makefile
  - makefile
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor
  - LICENSE