title: Gabriel — ML Research
description: Personal site
baseurl: ""
url: "https://g4br1el.github.io"

markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - Makefile
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor
